// Generated by https://quicktype.io

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class TopLevel
    {
        [JsonProperty("$schema")]
        public string Schema { get; set; }

        [JsonProperty("version")]
        public long Version { get; set; }

        [JsonProperty("newProjectRoot")]
        public string NewProjectRoot { get; set; }

        [JsonProperty("projects")]
        public Projects Projects { get; set; }

        [JsonProperty("defaultProject")]
        public string DefaultProject { get; set; }
    }

    public partial class Projects
    {
        [JsonProperty("demo1")]
        public Demo1 Demo1 { get; set; }
    }

    public partial class Demo1
    {
        [JsonProperty("projectType")]
        public string ProjectType { get; set; }

        [JsonProperty("schematics")]
        public Schematics Schematics { get; set; }

        [JsonProperty("root")]
        public string Root { get; set; }

        [JsonProperty("sourceRoot")]
        public string SourceRoot { get; set; }

        [JsonProperty("prefix")]
        public string Prefix { get; set; }

        [JsonProperty("architect")]
        public Architect Architect { get; set; }
    }

    public partial class Architect
    {
        [JsonProperty("build")]
        public Build Build { get; set; }

        [JsonProperty("serve")]
        public Serve Serve { get; set; }

        [JsonProperty("extract-i18n")]
        public ExtractI18N ExtractI18N { get; set; }

        [JsonProperty("test")]
        public Test Test { get; set; }
    }

    public partial class Build
    {
        [JsonProperty("builder")]
        public string Builder { get; set; }

        [JsonProperty("options")]
        public BuildOptions Options { get; set; }

        [JsonProperty("configurations")]
        public BuildConfigurations Configurations { get; set; }

        [JsonProperty("defaultConfiguration")]
        public string DefaultConfiguration { get; set; }
    }

    public partial class BuildConfigurations
    {
        [JsonProperty("production")]
        public Production Production { get; set; }

        [JsonProperty("development")]
        public Development Development { get; set; }
    }

    public partial class Development
    {
        [JsonProperty("buildOptimizer")]
        public bool BuildOptimizer { get; set; }

        [JsonProperty("optimization")]
        public bool Optimization { get; set; }

        [JsonProperty("vendorChunk")]
        public bool VendorChunk { get; set; }

        [JsonProperty("extractLicenses")]
        public bool ExtractLicenses { get; set; }

        [JsonProperty("sourceMap")]
        public bool SourceMap { get; set; }

        [JsonProperty("namedChunks")]
        public bool NamedChunks { get; set; }
    }

    public partial class Production
    {
        [JsonProperty("budgets")]
        public Budget[] Budgets { get; set; }

        [JsonProperty("fileReplacements")]
        public FileReplacement[] FileReplacements { get; set; }

        [JsonProperty("outputHashing")]
        public string OutputHashing { get; set; }
    }

    public partial class Budget
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("maximumWarning")]
        public string MaximumWarning { get; set; }

        [JsonProperty("maximumError")]
        public string MaximumError { get; set; }
    }

    public partial class FileReplacement
    {
        [JsonProperty("replace")]
        public string Replace { get; set; }

        [JsonProperty("with")]
        public string With { get; set; }
    }

    public partial class BuildOptions
    {
        [JsonProperty("outputPath", NullValueHandling = NullValueHandling.Ignore)]
        public string OutputPath { get; set; }

        [JsonProperty("index", NullValueHandling = NullValueHandling.Ignore)]
        public string Index { get; set; }

        [JsonProperty("main")]
        public string Main { get; set; }

        [JsonProperty("polyfills")]
        public string Polyfills { get; set; }

        [JsonProperty("tsConfig")]
        public string TsConfig { get; set; }

        [JsonProperty("assets")]
        public string[] Assets { get; set; }

        [JsonProperty("styles")]
        public string[] Styles { get; set; }

        [JsonProperty("scripts")]
        public object[] Scripts { get; set; }

        [JsonProperty("karmaConfig", NullValueHandling = NullValueHandling.Ignore)]
        public string KarmaConfig { get; set; }
    }

    public partial class ExtractI18N
    {
        [JsonProperty("builder")]
        public string Builder { get; set; }

        [JsonProperty("options")]
        public DevelopmentClass Options { get; set; }
    }

    public partial class DevelopmentClass
    {
        [JsonProperty("browserTarget")]
        public string BrowserTarget { get; set; }
    }

    public partial class Serve
    {
        [JsonProperty("builder")]
        public string Builder { get; set; }

        [JsonProperty("configurations")]
        public ServeConfigurations Configurations { get; set; }

        [JsonProperty("defaultConfiguration")]
        public string DefaultConfiguration { get; set; }
    }

    public partial class ServeConfigurations
    {
        [JsonProperty("production")]
        public DevelopmentClass Production { get; set; }

        [JsonProperty("development")]
        public DevelopmentClass Development { get; set; }
    }

    public partial class Test
    {
        [JsonProperty("builder")]
        public string Builder { get; set; }

        [JsonProperty("options")]
        public BuildOptions Options { get; set; }
    }

    public partial class Schematics
    {
        [JsonProperty("@schematics/angular:application")]
        public SchematicsAngularApplication SchematicsAngularApplication { get; set; }
    }

    public partial class SchematicsAngularApplication
    {
        [JsonProperty("strict")]
        public bool Strict { get; set; }
    }

    public partial class TopLevel
    {
        public static TopLevel FromJson(string json) => JsonConvert.DeserializeObject<TopLevel>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this TopLevel self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
